### ISSUE TITLE
Unable to implement this library on ESP32 WROVER-B

### ISSUE THREAD

**Issue by lnsriravichandran22** [peterhinch/micropython_eeprom#3]
Dear Pete!!

I hope that you are safe. 

I am getting this message when I try to run 
![Screenshot-Pete](https://user-images.githubusercontent.com/7059339/78891574-76c3bd80-7a85-11ea-8700-2abcfc3af8db.png)

FYI, I am using ESP32-Azure IoT Kit with ESP32-WROVER-B.

Please advise !!

**Comment by peterhinch** [comment]
Please could you explain what Flash chips you are using and how they are wired to the ESP32 chip.

The `wemos_flash.py` script is really intended for ESP8266 and I've only run it on that target. However the library should work on ESP32 if you are using supported chips and they are wired correctly.

**Comment by lnsriravichandran22** [comment]
Pete, As per the BOM , the flash part number is 'U3'. I could not find any reference to the part number of the flash memory anywhere!!

From the schematic of ESP32-WROVER-B , all I see the below pin mapping as follows :


![Falsh-side](https://user-images.githubusercontent.com/7059339/78968059-6bbe6b00-7b21-11ea-9da9-301efbda6906.PNG)
![ESP32-Side](https://user-images.githubusercontent.com/7059339/78968063-6cef9800-7b21-11ea-858d-c6670c308d1a.PNG)

The pin connections are as above.

Please advise!!

**Comment by peterhinch** [comment]
It's difficult for me to support an unknown chip. I'd intended these drivers to be used by people building their own hardware with one of the supported chips which I bought and tested. There is some standardisation of Flash devices in the form of a JEDEC spec, but yours may have some characteristic which is causing this behaviour. Even if we knew the chip type I'd have to buy some to investigate.

Assuming you've defined the pins correctly in the code the only thing I can think to try is to reduce the baudrate, say from 20MHz to 5MHz.

**Comment by MugenKadai** [comment]
Pete, I am extremely sorry.

This is a complete chaos and I assumed that these are intended for the internal flash memory that comes with ESP.

Thanks again for the work!!

**Comment by lnsriravichandran22** [comment]
Pete,

The mistake is all mine and hence the chaos.

I thought this is intended for internal Flash. 

Closing this. Sorry again for wasting your time!!
